unbind r
bind r source-file ~/.config/tmux/tmux.conf

#action key
unbind C-b
set-option -g prefix C-s
set-option -g repeat-time 300
set-option -g focus-events on

# set mouse option
set-option -g mouse on

#color set
set -g default-terminal "tmux-256color"

#split window
bind V split-window -v
bind H split-window -h

set-option -g status-position bottom 



# vim-like pane switching
bind-key k select-pane -U 
bind-key j select-pane -D 
bind-key h select-pane -L 
bind-key l select-pane -R 

# Moving window
bind-key -n C-S-Left select-window -t -1 
bind-key -n C-S-Right select-window -t +1 


# kill pane
unbind-key x
bind-key x kill-pane


set -g mouse on
set -g default-terminal "tmux-256color"

# Configure the catppuccin plugin
# For TPM, instead use `run ~/.tmux/plugins/tmux/catppuccin.tmux`

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Load catppuccin
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux


# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
# set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
# set -ag status-right "#{E:@catppuccin_status_uptime}"
#set -agF status-right "#{E:@catppuccin_status_battery}"

# run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
# run ~/.config/tmux/plugins/tmux-plugins/tmux-battery/battery.tmux
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

